name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler: 2.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      run: |
        bundle exec jekyll deploy
      if: github.ref == 'refs/heads/main'

    # Subir artefactos de construcción (actualizado a la versión v3)
    - name: Upload build artifact
      if: success()  # Solo subir artefactos si la construcción es exitosa
      uses: actions/upload-artifact@v3  # Usa la versión 3
      with:
        name: jekyll-build
        path: _site
